baseurl = "https://fanamo.github.io/website_1/"
title = "ファル速"
theme = "custom_theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = [ "\\.Rmd$", "\\.Rmarkdown$", "_cache$",]
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
paginate = 12
enableGitInfo = true
# googleAnalytics = "G-12345ABCDE"

[permalinks]
post = "/post/:year/:month/:day/:slug/"
# news = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
category = 'categories'
series = 'series'
tags = 'tags'

[params]
description = "A website built through Hugo and blogdown."
footer = "&copy; [Falcon]() 2023 | [利用規約](https://fanamo.github.io/website_1/terms/) | [サイトポリシー](https://fanamo.github.io/website_1/site_policy/) | [プライバシーポリシー](https://fanamo.github.io/website_1/privacy_policy/) | [広告掲載](https://fanamo.github.io/website_1/adv/) "
summary_length = 300
logo = "/static/images/logo.svg"
icon = 'pdf'

[params.text]
# back = "&larr; 戻る"
# edit = "進む &rarr;"
truncated = "&hellip;"

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[params.banner]
    src = "/images/logo.svg"
    alt = "logo"

[menu]
[[menu.main]]
name = "ホーム"
url = ""
weight = 1
icon = "rss"

# [[menu.main]]
# name = "タグ"
# url = "tags/"
# weight = 2
# icon = "rss"

# [[menu.main]]
# name = "カテゴリ"
# url = "categories/"
# weight = 3
# icon = "rss"

[[menu.main]]
name = "サイト情報"
url = "about/"
weight = 4
icon = "rss"

[[menu.main]]
name = "RSS"
url = "index.xml"
weight = 5
icon = "rss"


languageCode = "ja-jp"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    # contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Falcon News'
    weight = 2
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
  [languages.ja]
    # contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja-JP'
    languageDirection = 'ltr'
    languageName = 'Japan'
    title = 'ファル速'
    weight = 1
    [languages.ja.params]
      subtitle = 'エンタメニュース・話題の総合プラットフォーム'

[frontmatter]
  lastmod = ':fileModTime'