name: Create files, Push to repo

on:
  schedule:
    - cron: '* 0/5 0/1 ? * 1/1 *'
    # - cron: '*/5 6-7,12-13,18-19 * * 0-7' # per 5min 6:00-7, 12:00-13, 18:00-19
    # - cron: '0 12 * * *' # per day 12:00
    # - cron: '0 * * * *' # per hour 0min
    # - cron: '*/5 * * * *' # per min 5min
    # - cron: '*/5 * * * * *' # per sec 5sec
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  generate_post:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python scripts/run.py -i data/feeds.yaml -r -sl 10

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -a -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}